version: '3.9'
services:
    app:
        build: .
        ports:
            - '3000:3000'
        volumes:
            - .:/app
            - /app/node_modules
        env_file:
            - .env
        depends_on:
            - db
        command: npm run start
    db:
        image: postgres:15
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: backey_db
        ports:
            - '5432:5432'
        volumes:
            - pg_data:/var/lib/postgresql/data

volumes:
    pg_data:
